// polygon_sharp_cleaner.h —— 清理多边形尖角/狭长边
//
// 用法:对多边形重复移除内角 < angle_deg 的顶点(迭代移除"最尖"的那一个),
//      直到所有顶点都满足角度阈值或顶点数降到 3。
//
// 算法:类 Visvalingam-Whyatt,但不是按面积排序,而是按内角排序——
//      每次迭代扫描所有顶点,找到内角最小的那个,若小于阈值则移除。
//      每删一个顶点,周围两个顶点的内角会变化,所以需要重新扫描。
//
// 依赖:osg::Vec2d
// 作者:generated by Hermes for polygon3split project

#pragma once

#include <osg/Vec2d>
#include <vector>
#include <cmath>
#include <algorithm>
#include <cstddef>
#include <limits>
#include <stdexcept>
#include <string>

namespace poly_clean {

// ── 内角计算 ──────────────────────────────────────────────────────────
// 返回顶点 b 处的内角[弧度],其中 a 是前驱、c 是后继。
// 返回值范围(0, π),接近 0 = 极尖,接近 π = 平直。
inline double interior_angle_rad(const osg::Vec2d& a,
                                  const osg::Vec2d& b,
                                  const osg::Vec2d& c)
{
    osg::Vec2d ba = a - b;
    osg::Vec2d bc = c - b;
    double len_ba = ba.length();
    double len_bc = bc.length();
    if (len_ba < 1e-15 || len_bc < 1e-15)
        return 0.0;  // 退化边视为尖角,优先移除

    double cos_a = (ba * bc) / (len_ba * len_bc);
    cos_a = std::clamp(cos_a, -1.0, 1.0);
    return std::acos(cos_a);
}

// ── 角度阈值去尖角(核心) ──────────────────────────────────────────────
// 迭代移除内角 < angle_deg 的顶点,直到所有顶点满足阈值或剩余 3 个。
// 每次移除当前"最尖"的一个,然后重新扫描(因为邻接顶点的角度变了)。
//
// @param poly      输入多边形点列,简单不自交,顶点数 >= 3
// @param angle_deg 角度阈值(度),内角小于此值的顶点被移除,默认 5.0
// @return          清理后的多边形(顶点数 >= 3)
// @throws std::invalid_argument 如果输入多边形顶点数 < 3
inline std::vector<osg::Vec2d> remove_sharp_angles(
    const std::vector<osg::Vec2d>& poly,
    double angle_deg = 5.0)
{
    if (poly.size() < 3)
        throw std::invalid_argument(
            "polygon_sharp_cleaner: input polygon must have >= 3 vertices, got "
            + std::to_string(poly.size()));

    if (poly.size() == 3)
        return poly;  // 三角形,没法再删

    const double angle_thr_rad = angle_deg * M_PI / 180.0;
    std::vector<osg::Vec2d> res = poly;
    bool changed = true;

    while (changed && res.size() > 3) {
        changed = false;
        const std::size_t n = res.size();

        // 找当前环上内角最小的顶点
        std::size_t best_i = 0;
        double best_angle = std::numeric_limits<double>::max();

        for (std::size_t i = 0; i < n; ++i) {
            const auto& a = res[(i + n - 1) % n];
            const auto& b = res[i];
            const auto& c = res[(i + 1) % n];
            double ang = interior_angle_rad(a, b, c);
            if (ang < best_angle) {
                best_angle = ang;
                best_i = i;
            }
        }

        // 如果最尖的角都 >= 阈值,说明全部达标,退出
        if (best_angle >= angle_thr_rad)
            break;

        // 移除最尖的顶点
        res.erase(res.begin() + best_i);
        changed = true;  // 重新扫描
    }

    return res;
}

// ── 检查多边形是否自交(轻量版,仅用于调试/断言) ──────────────────────
// O(n²) 线段相交检测,不包含共享端点/邻接边的情况。
// 如果多边形较复杂,建议用 CGAL::Polygon_2::is_simple()。
inline bool is_simple(const std::vector<osg::Vec2d>& poly)
{
    const std::size_t n = poly.size();
    if (n < 4) return true;

    auto ccw = [](const osg::Vec2d& a, const osg::Vec2d& b, const osg::Vec2d& c) -> double {
        return (b.x() - a.x()) * (c.y() - a.y())
             - (c.x() - a.x()) * (b.y() - a.y());
    };

    auto seg_intersect = [&](std::size_t i1, std::size_t j1,
                              std::size_t i2, std::size_t j2) -> bool {
        // 排除邻接边(共享顶点的不算)
        if (i1 == i2 || i1 == j2 || j1 == i2 || j1 == j2)
            return false;
        const auto& p1 = poly[i1]; const auto& q1 = poly[j1];
        const auto& p2 = poly[i2]; const auto& q2 = poly[j2];
        double d1 = ccw(p1, q1, p2);
        double d2 = ccw(p1, q1, q2);
        double d3 = ccw(p2, q2, p1);
        double d4 = ccw(p2, q2, q1);
        if (((d1 > 0 && d2 < 0) || (d1 < 0 && d2 > 0)) &&
            ((d3 > 0 && d4 < 0) || (d3 < 0 && d4 > 0)))
            return true;
        // 共线/端点相交的情况忽略(简单多边形清理后很少出现)
        return false;
    };

    for (std::size_t i = 0; i < n; ++i) {
        std::size_t j = (i + 1) % n;
        for (std::size_t k = 0; k < n; ++k) {
            if (k == i || k == j) continue;
            std::size_t l = (k + 1) % n;
            if (seg_intersect(i, j, k, l))
                return false;
        }
    }
    return true;
}

} // namespace poly_clean